version: "3.7"
services:
    postgres:
        image: postgres:12.2
        restart: always
        container_name: postgres
        environment:
            POSTGRES_DB: securitydb
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: secret
            PGDATA: /var/lib/postgresql/data
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: kanishklikesprogramming@gmail.com
            PGADMIN_DEFAULT_PASSWORD: jaishreeram
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        ports:
            - "9092:80"
    redis:
      image: redis:6.2-alpine
      restart: always
      container_name: redis
      ports:
        - '6379:6379'
      command: redis-server --save 20 1 --loglevel warning
      volumes: 
        - redis-data:/data
            
volumes:
    db-data:
    pgadmin-data:
    redis-data:
    